### ISSUE TITLE
Makefile to fabfile.py

### ISSUE THREAD

**Issue by NathanUrwin** [NathanUrwin/cookie-cookie#7]
What do you think @abnerjacobsen ? I'm working on making a REST cookiecutter for Django, and moving from a `Makefile` calling `bin/*.py` scripts to one `fabfile.py`. The [Fabric API](http://www.fabfile.org/) is pretty awesome! ~~[Check it out](https://github.com/tuxredux/django-lightsail/blob/master/fabfile.py).~~

**Comment by abnerjacobsen** [comment]
@tuxredux I know very little about Fabric - I used it only once on a project a long time ago. The only limitation I see in it is the lack of support for Python 3.X, at least that's what it says in the documentation.

If Python 3 support is required there is a project that came up from Fabric that might be useful: https://github.com/pyinvoke/invoke - http://www.pyinvoke.org/faq.html

An example of using Invoke with a remote API, like your project with Django:

Https://github.com/Temelio/ovh_api_tasks

Another example: https://github.com/scheparev-moberries/invoke-github-flow

I hope I have helped.

**Comment by tuxredux** [comment]
Hey @abnerjacobsen :wave: This was a big help! Thank you!

So your comment led me to the [Development Roadmap for Fabric](http://www.fabfile.org/roadmap.html) which has invaluable information about Invoke, Fabric 2.x and Patchwork.

I did not realize the local CLI and SSH task runners were being separated into two different libraries, or about the lack of Python 3 support :thinking: 

[The **Python 3 support** issue recommends using a fork, Fabric3.](https://github.com/fabric/fabric/issues/1424#issuecomment-179552669) I will give it a go, and make sure it is a viable solution before switching! :+1: 

Would you still use `cookie-cookie` if it had a `fabfile.py` instead of a `Makefile`? I am not a fan of `make` :laughing: 

If not, I can add a `"task_runner": ["fabric", "make"],` cookiecutter option. Let me know what you think!

**Comment by abnerjacobsen** [comment]
@tuxredux For me, there is no problem switching Make through a solution using python, I'm also thinking about doing this in my projects.

off topic: 

From what I understood from your https://github.com/tuxredux/django-lightsail project its goal is to provision a Django installation in the Amazon lightsail, correct?

I'm working on a similar project but instead of setting up a server for the specific needs of an application I use docker to run a container configured for the application's features so I do not need to change anything on the physical server, just send it to it a docker-compose.yml file.

Once the container's docker are running all the configurations are done via a rest API or by the web control panel which is a Flask application.

Some of the features currently available are:

- The system runs on a local or remote computer without any changes in the physical machines or the need to install any package other than docker.
- Letsencrypt SSL certificates or self-signed (when using the local computer)
- Engines for PHP 5.6, 7.0, 7.1 and static sites
- Installation of apps like Grav, Wordpress, Nextcloud and others from any ZIP file available on the web
- File manager using Minio
- Upload / download files using the S3 protocol
- BD MySql with admin using Adminer
- Redis to cache PHP sections and notifications to various system components using PubSub.

See information about it in these links:

Https://daspanel.com/
Https://github.com/daspanel/daspanel

Sorry for the lengthy advertisement of my project but, who knows, you could use it. To use Django or any other app in Python it would be necessary to develop a compatable engine. See an example at: https://github.com/daspanel/engine-php71

The documentation is out of date because I am working on a new version that I will release until next week.

**Comment by tuxredux** [comment]
Hey @abnerjacobsen :wave:

Glad to hear you don't mind using a `fabfile.py`! I will replace the `Makefile` with one here in the nearby future :+1: Yeah, that's correct. Although I'll probably transform that repository into the `cookiecutter-rest` project I mentioned.

I checked out the [Daspanel GitHub Organization](https://github.com/daspanel). Looks pretty interesting! Being able to manipulate a web server configuration through its own RESTful API sounds like a cool idea!

Although personally, I'm not a fan of Docker, but that's probably just because I ran into problems running it on my Debian box. I will eventually have to get it running though, since you need Docker to run Headless Chrome for [lighthouse-ci]().
